theme: minima
title: KrioVoice 
description: KrioVoice is a seamless Text-to-Speech (TTS) and Speech-to-Text (STT) for the Krio language, making communication smarter and more accessible.
author: David Conteh
